INSERT INTO UZYTKOWNICY(NAZWA, HASLO, IMIE, NAZWISKO, ROLA, NAZWA_KIEROWNIKA)
VALUES ('j4ku6','$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG','Jakub','Lechnicki','Klient',null);
INSERT INTO UZYTKOWNICY(NAZWA, HASLO, IMIE, NAZWISKO, ROLA, NAZWA_KIEROWNIKA)
VALUES ('nowak1234','$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG','Dawid','Nowakowski','Kierownik',null);
INSERT INTO UZYTKOWNICY(NAZWA, HASLO, IMIE, NAZWISKO, ROLA, NAZWA_KIEROWNIKA)
VALUES ('sebix666','$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG','Sebastian','Germanski','Pracownik','nowak1234');
INSERT INTO UZYTKOWNICY(NAZWA, HASLO, IMIE, NAZWISKO, ROLA, NAZWA_KIEROWNIKA)
VALUES ('roman89','$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG','Pawel','Romanowski','Pracownik','nowak1234');
INSERT INTO UZYTKOWNICY(NAZWA, HASLO, IMIE, NAZWISKO, ROLA, NAZWA_KIEROWNIKA)
VALUES ('Ferdydurke','$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG','Witold','Piasecki','Kierownik',null);
INSERT INTO UZYTKOWNICY(NAZWA, HASLO, IMIE, NAZWISKO, ROLA, NAZWA_KIEROWNIKA)
VALUES ('haB17','$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG','Anastazja','Drezniecka','Klient',null);
INSERT INTO UZYTKOWNICY(NAZWA, HASLO, IMIE, NAZWISKO, ROLA, NAZWA_KIEROWNIKA)
VALUES ('tom99','$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG','Tomasz','Kowalski','Pracownik','Ferdydurke');
INSERT INTO UZYTKOWNICY(NAZWA, HASLO, IMIE, NAZWISKO, ROLA, NAZWA_KIEROWNIKA)
VALUES ('dziwak','$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG','Jan','Nowakowski','Klient',null);
INSERT INTO UZYTKOWNICY(NAZWA, HASLO, IMIE, NAZWISKO, ROLA, NAZWA_KIEROWNIKA)
VALUES ('texter','$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG','Jan','Piasecki','Pracownik','Ferdydurke');
INSERT INTO UZYTKOWNICY(NAZWA, HASLO, IMIE, NAZWISKO, ROLA, NAZWA_KIEROWNIKA)
VALUES ('gedyr','$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG','Jakub','Tkacz','Pracownik','nowak1234');

INSERT INTO HOTELE(NAZWA, MIASTO, ULICA, OCENA, NAZWA_KIEROWNIKA)
VALUES ('Apollo','Wroclaw','Karlowicza',3,'nowak1234');
INSERT INTO HOTELE(NAZWA, MIASTO, ULICA, OCENA, NAZWA_KIEROWNIKA)
VALUES ('Bolimowo','Szczecin','Koszalinska',5,'Ferdydurke');

INSERT INTO POKOJE(NUMER, RODZAJ, ROZMIAR, CENA, ID_HOTELU)
VALUES (1,1,1,200.00,2);
INSERT INTO POKOJE(NUMER, RODZAJ, ROZMIAR, CENA, ID_HOTELU)
VALUES (1,2,1,80.00,1);
INSERT INTO POKOJE(NUMER, RODZAJ, ROZMIAR, CENA, ID_HOTELU)
VALUES (2,3,2,100.00,1);
INSERT INTO POKOJE(NUMER, RODZAJ, ROZMIAR, CENA, ID_HOTELU)
VALUES (3,4,3,120.50,1);

INSERT INTO REZERWACJE(ID_POKOJU, NAZWA_KLIENTA, DATA_ROZPOCZECIA, DATA_ZAKONCZENIA)
VALUES (1,'dziwak','2020-01-12','2020-01-15');
INSERT INTO REZERWACJE(ID_POKOJU, NAZWA_KLIENTA, DATA_ROZPOCZECIA, DATA_ZAKONCZENIA)
VALUES (3,'j4ku6','2020-06-12','2020-07-02');
INSERT INTO REZERWACJE(ID_POKOJU, NAZWA_KLIENTA, DATA_ROZPOCZECIA, DATA_ZAKONCZENIA)
VALUES (2,'haB17','2020-01-12','2020-01-15');
